markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [branding]
github_url      : "https://github.com/datacarpentry"
swc_prefix      : "http://datacarpentry.org"
twitter_name    : "@datacarpentry"
defaults:
  scope:
    path : "lessons" # an empty string here means all files in the project
  values:
    layout : "lesson"
